####liger analysis 
##input data are the expression matrix download from the GEO
##output data includes normalized expression matrix and cell type annotation file
library(liger)
dataset1 <- read.table("GSE138826_expression_matrix.txt",row.names=1,header=TRUE,sep='\t')
dataset2 <- read.table("GSE143435_expression_matrix.txt",row.names=1,header=TRUE,sep='\t')
dataset2 <- read.table("GSE143437_expression_matrix.txt",row.names=1,header=TRUE,sep=',')
ifnb_liger <- createLiger(list(Dataset1 = dataset1, Dataset2 = dataset2,Dataset3=dataset3))
ifnb_liger <- normalize(ifnb_liger)
ifnb_liger <- selectGenes(ifnb_liger)
ifnb_liger <- scaleNotCenter(ifnb_liger)
ifnb_liger <- optimizeALS(ifnb_liger, k = 20)
ifnb_liger <- quantile_norm(ifnb_liger)
ifnb_liger <- louvainCluster(ifnb_liger, resolution = 0.4)
ifnb_liger <- runUMAP(ifnb_liger, distance = 'cosine', n_neighbors = 30, min_dist = 0.3)
cluster.results <- runWilcoxon(ifnb_liger, compare.method = "clusters")
cluster.results <- cluster.results[cluster.results$padj < 0.05,]
cluster.results <- cluster.results[cluster.results$logFC > 3,]
write.csv(cluster.results,file="cluster_marker_gene.csv")
id<-ifnb_liger@clusters
num<-which(levels(id)==7)
levels(id)[num]<-c('Musc')
num<-which(levels(id)==3)
levels(id)[num]<-c('Eosinophils')
num<-which(levels(id)==0)
levels(id)[num]<-c('FAPs')
num<-which(levels(id)==5)
levels(id)[num]<-c('FAPs')
num<-which(levels(id)==2)
levels(id)[num]<-c('Neutrophils')
num<-which(levels(id)==9)
levels(id)[num]<-c('B&T cells')
num<-which(levels(id)==4)
levels(id)[num]<-c('Fibroblasts')
num<-which(levels(id)==11)
levels(id)[num]<-c('Endothelial')
num<-which(levels(id)==12)
levels(id)[num]<-c('Glial Cells')
num<-which(levels(id)==10)
levels(id)[num]<-c('Smooth Muscle')
num<-which(levels(id)==8)
levels(id)[num]<-c('Mature skeletal muscle')
num<-which(levels(id)==1)
levels(id)[num]<-c('Macrophages')
num<-which(levels(id)==6)
levels(id)[num]<-c('Myoblast')
ifnb_liger@clusters<-id
all.plots <- plotByDatasetAndCluster(ifnb_liger, axis.labels = c('UMAP 1', 'UMAP 2'), return.plots = T)
all.plots[[1]] + all.plots[[2]]
write.csv(ifnb_liger@clusters,file="cell_type_annotation.csv")